name: End to End

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        ghc: ["8.8.4"]
        spec:
          - "0.16.1"
        node:
          - 20

    steps:
      - uses: actions/checkout@v3

      - name: Setup node v${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: NPM install
        run: npm install

      - name: Setup Motoko tools
        run: |
          sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"
          moc --version
          moc --help

      - name: mops install
        run: |
          npm install -g ic-mops
          mops install

      - name: Setup dfx
        uses: dfinity/setup-dfx@main
        with:
          dfx-version: "0.25.0"

      - name: Start dfx
        run: |
          dfx --version
          dfx start --background
          sleep 5

      - name: Build all canisters
        run: |
          dfx deps pull
          dfx generate
          dfx build
          dfx deploy
          dfx stop

      - name: Check Lint
        run: npm run lint

      - name: Run tests
        run: npm run test
        env:
          CI: true
          REPLICA_PORT: 8000
